// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: guest.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertGuest = `-- name: InsertGuest :one
INSERT INTO booking.guests (id, first_name, last_name, email)
VALUES ($1, $2, $3, $4)
RETURNING id, first_name, last_name, email
`

type InsertGuestParams struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
}

func (q *Queries) InsertGuest(ctx context.Context, arg InsertGuestParams) (BookingGuest, error) {
	row := q.db.QueryRowContext(ctx, insertGuest,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
	)
	var i BookingGuest
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
	)
	return i, err
}
