FROM  golang:1.25-alpine AS build
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main cmd/cron/inventory/main.go

FROM alpine:3.22.1
WORKDIR /app
COPY --from=build /app/main /app/main
RUN apk update && apk upgrade

CMD ["./main"]
