apiVersion: v1
kind: Secret
metadata:
  name: psql-credentials
type: Opaque
data:
  db-username: YWxleA==
  db-password: cGFzc3dvcmQxMjM0
  jwt-secret: c3VwZXJzZWNyZXRrZXk=
  database-url: cG9zdGdyZXM6Ly9hbGV4OnBhc3N3b3JkMTIzNEBob3N0LmRvY2tlci5pbnRlcm5hbDo1NDgzL2Jvb2tpbmc/c3NsbW9kZT1kaXNhYmxl
