apiVersion: batch/v1
kind: CronJob
metadata:
  name: hotel-system-inventory
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hotel-system-inventory-cron
            image: hotel-system-inventory-cron:latest
            resources:
              requests:
                memory: "128Mi"
              limits:
                memory: "128Mi"
          restartPolicy: OnFailure
